version: '3.8'

services:
  bot:
    build: .
    image: storeman-bot:local
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/storeman
    secrets:
      - source: dotenv
        target: /app/.env
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

secrets:
  dotenv: 
    file: ./.env
